language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit

notifications:
    email: false
