language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit

notifications:
    email: false
