language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit

notifications:
    email: false
